export default {
login: "AzizurRahmanEmon",
id: 47455161,
node_id: "MDQ6VXNlcjQ3NDU1MTYx",
avatar_url: "https://avatars.githubusercontent.com/u/47455161?v=4",
gravatar_id: "",
url: "https://api.github.com/users/AzizurRahmanEmon",
html_url: "https://github.com/AzizurRahmanEmon",
followers_url: "https://api.github.com/users/AzizurRahmanEmon/followers",
following_url: "https://api.github.com/users/AzizurRahmanEmon/following{/other_user}",
gists_url: "https://api.github.com/users/AzizurRahmanEmon/gists{/gist_id}",
starred_url: "https://api.github.com/users/AzizurRahmanEmon/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/AzizurRahmanEmon/subscriptions",
organizations_url: "https://api.github.com/users/AzizurRahmanEmon/orgs",
repos_url: "https://api.github.com/users/AzizurRahmanEmon/repos",
events_url: "https://api.github.com/users/AzizurRahmanEmon/events{/privacy}",
received_events_url: "https://api.github.com/users/AzizurRahmanEmon/received_events",
type: "User",
site_admin: false,
name: "Azizur Rahman",
company: null,
blog: "",
location: "Uttara,Dhaka,Bangladesh",
email: null,
hireable: null,
bio: "Trying to be better each day
",
twitter_username: null,
public_repos: 8,
public_gists: 0,
followers: 0,
following: 1,
created_at: "2019-02-08T15:33:19Z",
updated_at: "2022-08-23T23:30:28Z"
}
